provider "proxmox" {
  endpoint  = var.proxmox_endpoint
  api_token = var.proxmox_api_token

  insecure = true # Self-signed cert on Proxmox

  ssh {
    agent    = true
    username = "glenn"
  }
}

# ── Cloud image (downloaded once, reused for all VMs) ────────────────────

resource "proxmox_download_file" "debian13_cloud" {
  content_type = "iso"
  datastore_id = var.cloud_image_storage
  node_name    = var.proxmox_node
  file_name    = "debian-13-generic-amd64.img"

  url = "https://cloud.debian.org/images/cloud/trixie/daily/latest/debian-13-generic-amd64-daily.qcow2"

  lifecycle {
    prevent_destroy = true
  }
}

# ── Cloud-init config ────────────────────────────────────────────────────

resource "proxmox_virtual_environment_file" "cloud_config" {
  content_type = "snippets"
  datastore_id = var.cloud_image_storage
  node_name    = var.proxmox_node

  source_raw {
    data = <<-EOF
      #cloud-config
      hostname: ${var.vm_name}
      fqdn: ${var.vm_name}.local

      users:
        - name: root
          lock_passwd: false
          ssh_authorized_keys:
            - ${var.ssh_public_key}
        - name: glenn
          groups: sudo
          shell: /bin/bash
          sudo: ALL=(ALL) NOPASSWD:ALL
          ssh_authorized_keys:
            - ${var.ssh_public_key}

      # Format and mount the data disk
      disk_setup:
        /dev/sdb:
          table_type: gpt
          layout: true
          overwrite: false

      fs_setup:
        - label: data
          filesystem: ext4
          device: /dev/sdb1
          overwrite: false

      mounts:
        - ["/dev/sdb1", "/data", "ext4", "defaults,noatime", "0", "2"]

      # Install qemu-guest-agent so Terraform can read the IP
      packages:
        - qemu-guest-agent
        - python3
        - sudo

      runcmd:
        - systemctl enable --now qemu-guest-agent
        - mkdir -p /data
    EOF

    file_name = "${var.vm_name}-cloud-config.yaml"
  }
}

# ── VM ───────────────────────────────────────────────────────────────────

resource "proxmox_virtual_environment_vm" "geocoder" {
  name      = var.vm_name
  node_name = var.proxmox_node
  vm_id     = var.vm_id > 0 ? var.vm_id : null
  pool_id   = var.resource_pool

  description = "Nomirevturbo geocoder test VM - managed by Terraform"
  tags        = ["terraform", "geocoder", "test"]

  # Hardware
  cpu {
    cores = var.vm_cores
    type  = "host"
  }

  memory {
    dedicated = var.vm_memory
  }

  # OS disk - cloned from cloud image
  disk {
    datastore_id = var.os_disk_storage
    interface    = "scsi0"
    size         = var.os_disk_size
    file_id      = proxmox_download_file.debian13_cloud.id
    file_format  = "raw"
  }

  # Data disk (/data) for PBF downloads + geocoder index
  disk {
    datastore_id = var.data_disk_storage
    interface    = "scsi1"
    size         = var.data_disk_size
    file_format  = "raw"
  }

  # SCSI controller
  scsi_hardware = "virtio-scsi-single"

  # Network
  network_device {
    bridge = var.network_bridge
    model  = "virtio"
  }

  # Boot from cloud image disk
  boot_order = ["scsi0"]
  bios       = "seabios"

  # Cloud-init
  initialization {
    datastore_id      = var.os_disk_storage # cloud-init drive on same storage as OS
    user_data_file_id = proxmox_virtual_environment_file.cloud_config.id

    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
  }

  # Guest agent (cloud-init installs it)
  agent {
    enabled = true
  }

  operating_system {
    type = "l26"
  }
}

# ── Ansible inventory (generated) ────────────────────────────────────────

locals {
  # Pick the first non-loopback IPv4 address
  vm_ip = [
    for addrs in proxmox_virtual_environment_vm.geocoder.ipv4_addresses :
    addrs[0] if addrs[0] != "127.0.0.1"
  ][0]
}

resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/../ansible/inventory/test.yml"
  file_permission = "0644"
  content         = <<-EOF
    ---
    # Generated by Terraform - do not edit manually
    all:
      hosts:
        ${var.vm_name}:
          ansible_host: "${local.vm_ip}"
          ansible_user: glenn
          ansible_become: true
          ansible_python_interpreter: /usr/bin/python3

      vars:
        geocoder_enabled: true
        geocoder_port: 3456
        geocoder_bind: "0.0.0.0"
        geocoder_search_distance: 75
        geocoder_street_level: 17
        geocoder_admin_level: 10

        # Europe extract (25 GB download)
        geocoder_europe_pbf_url: "https://download.geofabrik.de/europe-latest.osm.pbf"
        geocoder_europe_pbf_path: "/data/pbf/europe-latest.osm.pbf"

        # Data disk mounted at /data
        geocoder_data_dir: "/data/geocoder"
        geocoder_index_dir: "/data/geocoder/index"
        geocoder_build_dir: "/data/geocoder/build"
  EOF
}

# ── Outputs ──────────────────────────────────────────────────────────────

output "vm_id" {
  description = "Proxmox VM ID"
  value       = proxmox_virtual_environment_vm.geocoder.vm_id
}

output "vm_name" {
  description = "VM name"
  value       = proxmox_virtual_environment_vm.geocoder.name
}

output "vm_ip" {
  description = "VM IPv4 address"
  value       = local.vm_ip
}

output "ansible_command" {
  description = "Run this to provision the VM"
  value       = "ansible-playbook -i ansible/inventory/test.yml ansible/playbook.yml"
}
