# Copyright 2026 Glenn Plas / Bitless BVBA
# SPDX-License-Identifier: Apache-2.0

---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart geocoder
  ansible.builtin.systemd:
    name: geocoder
    state: restarted

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
