# Copyright 2026 Glenn Plas / Bitless BVBA
# SPDX-License-Identifier: Apache-2.0

---
- name: Create geocoder directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ geocoder_user }}"
    group: "{{ geocoder_group }}"
    mode: "0755"
  loop:
    - "{{ geocoder_data_dir }}"
    - "{{ geocoder_index_dir }}"

- name: Create geocoder install directory
  ansible.builtin.file:
    path: "{{ geocoder_install_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
