# Copyright 2026 Glenn Plas / Bitless BVBA
# SPDX-License-Identifier: Apache-2.0

---
- name: Template geocoder systemd service
  ansible.builtin.template:
    src: geocoder.service.j2
    dest: /etc/systemd/system/geocoder.service
    mode: "0644"
  notify:
    - Reload systemd
    - Restart geocoder

- name: Enable and start geocoder service
  ansible.builtin.systemd:
    name: geocoder
    enabled: true
    state: started
    daemon_reload: true
